name: build-tintin
run-name: Tintin - ${{ github.actor }} by ${{ github.event_name }} ${{ github.ref }}
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "**"
      - "!README.md"
      - "!.github/**"
  pull_request:
    branches:
      - main
    paths:
      - "**"
      - "!README.md"
      - "!.github/**"

jobs:
  docker:
    runs-on: arc-runner-set
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v5.0.0-beta2
        id: version

      - name: Echo Version
        run: echo "Version would be ${{ steps.version.outputs.version }}"

      - name: Build and Push Docker PR
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          #context: "{{defaultContext}}:tintin"
          push: false
          tags: faliarin/tintin:latest,faliarin/tintin:${{ steps.version.outputs.version }}

      - name: Build and Push Docker Master Branch
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          #context: "{{defaultContext}}:tintin"
          push: true
          tags: faliarin/tintin:latest,faliarin/tintin:${{ steps.version.outputs.version }}
          provenance: mode=max
          sbom: true

      - name: Tag Release (vX.Y.Z)
        if: github.event_name != 'pull_request'
        run: |
          git tag ${{ steps.version.outputs.version_tag }}
          git push origin ${{ steps.version.outputs.version_tag }}
